chore: improve error handling in `Containerfile`
This eliminates the following SAST finding reported by Coverity:
```
Error: SIGMA.shell_missing_pipefail (CWE-393):
Containerfile:43: Sigma main event: The Dockerfile command directs output through the pipe operator `|` without enabling the shell option `pipefail`. As a result, the exit code will be determined by the success or failure of the last command, ignoring any upstream failures in the pipe chain. This can result in unexpected behavior due to undetected build failures.
Containerfile:43: remediation: Explicitly set the `pipefail` option for the current shell context when using the pipe operator `|`.
   41|
   42|   # install uv, install local dependencies and initialize version string
   43|-> RUN pip3 install --no-cache-dir gssapi uv \
   44|       && uv sync --no-cache --frozen \
   45|       && printf '\n[tool.hatch.version.raw-options]\nfallback_version = "%s"\n' \
```

Related: https://issues.redhat.com/browse/AEGIS-78