fix: make Gemini work with `pydantic-ai-slim-1.46.0`
After the update of `pydantic-ai-slim` from 1.44.0 to 1.46.0,
all LLM requests to Gemini API started to fail with:
```
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: gemini-2.5-flash, body: {'error': {'code': 400, 'message': 'Manually set deadline 5s is too short. Minimum allowed deadline is 10s.', 'status': 'INVALID_ARGUMENT'}}
```