chore: unpin the `logfire` version
The pinned version of `logfire` prevented the `aegis-ai 0.5.0` PyPI
package from being installed:
```
ERROR: Cannot install logfire and logfire[fastapi,httpx,sqlite3]==4.15.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.60b1 depends on opentelemetry-instrumentation==0.60b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.60b0 depends on opentelemetry-instrumentation==0.60b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.59b0 depends on opentelemetry-instrumentation==0.59b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.58b0 depends on opentelemetry-instrumentation==0.58b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.57b0 depends on opentelemetry-instrumentation==0.57b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.56b0 depends on opentelemetry-instrumentation==0.56b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.55b1 depends on opentelemetry-instrumentation==0.55b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.55b0 depends on opentelemetry-instrumentation==0.55b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.54b1 depends on opentelemetry-instrumentation==0.54b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.54b0 depends on opentelemetry-instrumentation==0.54b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.53b1 depends on opentelemetry-instrumentation==0.53b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.53b0 depends on opentelemetry-instrumentation==0.53b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.52b1 depends on opentelemetry-instrumentation==0.52b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.52b0 depends on opentelemetry-instrumentation==0.52b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.51b0 depends on opentelemetry-instrumentation==0.51b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.50b0 depends on opentelemetry-instrumentation==0.50b0
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.49b2 depends on opentelemetry-instrumentation==0.49b2
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.49b1 depends on opentelemetry-instrumentation==0.49b1
    logfire 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    logfire[fastapi,httpx,sqlite3] 4.15.1 depends on opentelemetry-instrumentation>=0.41b0
    opentelemetry-instrumentation-fastapi 0.49b0 depends on opentelemetry-instrumentation==0.49b0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Related: https://github.com/RedHatProductSecurity/aegis-ai/pull/370