fix: make Gemini API work with lower `AEGIS_LLM_TIMEOUT_SECS`
If `AEGIS_LLM_TIMEOUT_SECS` was set to a value below 10, the Gemini API
refused the requests immediately rather than processing them for the
specified amount of time.

Reproducer:
```sh
% AEGIS_LLM_TIMEOUT_SECS=9 uv run aegis identify-pii CVE-2026-1200
[...]
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: gemini-2.5-flash, body: {'error': {'code': 400, 'message': 'Manually set deadline 9s is too short. Minimum allowed deadline is 10s.', 'status': 'INVALID_ARGUMENT'}}
```

Related: commit 74a8732ad6b5afde7bd6e33752fe0391126ffc30