fix: make aegis work again with `ollama`
`ollama` does not accept `\d` in regular expressions, which results
in the following, difficult to debug, failure:
```
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: mistral:7b-v3, body: {'code': 400, 'message': 'Failed to parse grammar', 'type': 'invalid_request_error'}
```

Note that if we apply this one-line patch on commit
b351bf6fc258b3cb4564cabb57106c37b6757205, it does not fix the bug on its
own because the commit introduced other issues with `ollama`, which were
later fixed by commit 5934a9061154de2a890a37cad7ea06223cef4590 (although
the other commit is not tagged as a fix).

Fixes: commit b351bf6fc258b3cb4564cabb57106c37b6757205
Fixes: https://github.com/RedHatProductSecurity/aegis-ai/issues/146
Related: https://github.com/ollama/ollama/issues/10591
Related: https://issues.redhat.com/browse/AEGIS-118