fix: do not return `None` from `run_if_safe()`
This causes a misleading failure instead of propagating the cause:
```
AttributeError: 'NoneType' object has no attribute 'output'
```

Related: https://issues.redhat.com/browse/AEGIS-185