chore: drop `Containerfile.eval` no longer maintained
This eliminates the following SAST finding reported by Coverity:
```
Error: SIGMA.unspecified_software_version (CWE-829):
Containerfile.eval:1: Sigma main event: The Dockerfile `FROM` instruction does not pin the docker image to a stable version. Pinning the version of the base image will make the container being built more predictable. Relying on the latest version may silently inherit newer packages, which may affect application reliability or introduce security vulnerabilities.
Containerfile.eval:1: remediation: Explicitly pin the image version to a stable version.
    1|-> FROM registry.access.redhat.com/ubi10-minimal
    2|
    3|   # install required RPM packages
```

Related: https://issues.redhat.com/browse/AEGIS-78