fix: update pydantic-ai to 0.7.4
It turned out that commit 0a5e244b1d5a969823fa8644035536ad1fd59293
accidentally reverted commit c5e1a4452feab3fa44f230edc865cbdd445cb0ba
which caused Aegis to fail with OpenAI-provided models:
```
Traceback (most recent call last):
  File "/home/kdudka/git/aegis/.venv/bin/aegis", line 10, in <module>
    sys.exit(aegis_cli())
             ~~~~~~~~~^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/home/kdudka/git/aegis/src/aegis_ai_cli/main.py", line 118, in suggest_impact
    result = asyncio.run(_doit())
  File "/usr/lib64/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/kdudka/git/aegis/src/aegis_ai_cli/main.py", line 116, in _doit
    return await feature.exec(cve_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/src/aegis_ai/features/cve/__init__.py", line 62, in exec
    return await self.run_if_safe(prompt, output_type=SuggestImpactModel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/src/aegis_ai/features/__init__.py", line 18, in run_if_safe
    return await self.agent.run(prompt.to_string(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/agent.py", line 474, in run
    async for _ in agent_run:
        pass
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/agent.py", line 2005, in __anext__
    next_node = await self._graph_run.__anext__()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_graph/graph.py", line 771, in __anext__
    return await self.next(self._next_node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_graph/graph.py", line 744, in next
    self._next_node = await node.run(ctx)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/_agent_graph.py", line 302, in run
    return await self._make_request(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/_agent_graph.py", line 362, in _make_request
    model_response = await ctx.deps.model.request(message_history, model_settings, model_request_parameters)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/models/openai.py", line 246, in request
    response = await self._completions_create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        messages, False, cast(OpenAIModelSettings, model_settings or {}), model_request_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/models/openai.py", line 315, in _completions_create
    openai_messages = await self._map_messages(messages)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/models/openai.py", line 486, in _map_messages
    tool_calls.append(self._map_tool_call(item))
                      ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/kdudka/git/aegis/.venv/lib64/python3.13/site-packages/pydantic_ai/models/openai.py", line 508, in _map_tool_call
    return chat.ChatCompletionMessageToolCallParam(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        id=_guard_tool_call_id(t=t),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        type='function',
        ^^^^^^^^^^^^^^^^
        function={'name': t.tool_name, 'arguments': t.args_as_json_str()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/typing.py", line 1317, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/usr/lib64/python3.13/typing.py", line 560, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union
```

Related: https://github.com/RedHatProductSecurity/aegis-ai/pull/126
Related: https://issues.redhat.com/browse/AEGIS-110